# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fir128/fir128.xci
# IP: The module: 'fir128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fir128/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fir128/fir128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fir128/fir128.xci
# IP: The module: 'fir128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fir128/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fir128/fir128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
