# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool_2/conv_relu_pool_2.cache/wt [current_project]
set_property parent.project_path /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool_2/conv_relu_pool_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool_2_exp/conv_relu_pool_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/nezin/Documents/ECE395A/vhdl/conv/coefs/conv0_0.coe
add_files /home/nezin/Documents/ECE395A/vhdl/conv/coefs/conv0_1.coe
read_vhdl -library xil_defaultlib {
  /home/nezin/Documents/ECE395A/vhdl/source/conv_0.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/conv_1.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/conv_layer_0.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/conv_layer_1.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/downsample.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/maxpool.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/mux2_1.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/relu.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/conv_relu_pool.vhd
}
read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_1/fir128_1.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_1/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_1/fir128_1_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_1/fir128_1.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_0/fir128_0.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_0/fir128_0_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_0/fir128_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top conv_relu_pool -part xc7z020clg484-1


write_checkpoint -force -noxdef conv_relu_pool.dcp

catch { report_utilization -file conv_relu_pool_utilization_synth.rpt -pb conv_relu_pool_utilization_synth.pb }
