# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16.xci
# IP: The module: 'fifo_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16.xci
# IP: The module: 'fifo_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
