# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/fully_connected_coefficients_1/fully_connected_coefficients_1.xci
# IP: The module: 'fully_connected_coefficients_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/fully_connected_coefficients_1/fully_connected_coefficients_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fully_connected_coefficients_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/fully_connected_coefficients_1/fully_connected_coefficients_1.xci
# IP: The module: 'fully_connected_coefficients_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/fully_connected_coefficients_1/fully_connected_coefficients_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fully_connected_coefficients_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
