# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.cache/wt [current_project]
set_property parent.project_path /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/nezin/Documents/ECE395A/vhdl/helpers/conv_2/conv_2_test_rom.coe
read_vhdl -library xil_defaultlib {
  /home/nezin/Documents/ECE395A/vhdl/inner_product_fifo/inner_product_fifo.srcs/sources_1/new/dot.vhd
  /home/nezin/Documents/ECE395A/vhdl/conv/conv.srcs/sources_1/new/mux2_1.vhd
  /home/nezin/Documents/Maia/vhdl/source/conv2_controller.vhd
}
read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/inner_product_fifo/inner_product_fifo.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/inner_product_fifo/inner_product_fifo.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/inner_product_fifo/inner_product_fifo.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/filter_rom/filter_rom.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/filter_rom/filter_rom_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/filter_rom/filter_rom.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/fifo_64/fifo_64.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/fifo_64/fifo_64.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/fifo_64/fifo_64_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/fifo_64/fifo_64.xci]

read_ip -quiet /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/Maia/vhdl/conv_2/conv_2.srcs/sources_1/ip/fifo_16/fifo_16.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/fifo_45/fifo_45.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/fifo_45/fifo_45.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/fifo_45/fifo_45_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_2_controller/conv_2_controller.srcs/sources_1/ip/fifo_45/fifo_45.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top conv2_controller -part xc7z020clg484-1


write_checkpoint -force -noxdef conv2_controller.dcp

catch { report_utilization -file conv2_controller_utilization_synth.rpt -pb conv2_controller_utilization_synth.pb }
