# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nezin/Documents/ECE395A/vhdl/inner_product_fifo/inner_product_fifo.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_multadd_0 || ORIG_REF_NAME==xbip_multadd_0}]

# IP: ip/filter_rom/filter_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==filter_rom || ORIG_REF_NAME==filter_rom}]
