# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.cache/wt [current_project]
set_property parent.project_path /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/nezin/helpers/conv_2/conv_2_test_rom.coe
add_files /home/nezin/Documents/ECE395A/vhdl/helpers/conv_2/conv_2_test_rom.coe
read_vhdl -library xil_defaultlib {
  /home/nezin/Documents/ECE395A/vhdl/source/conv2_controller.vhd
  /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/new/conv_unit.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/dot.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/downsample.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/maxpool.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/mux2_1.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/relu.vhd
  /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/new/conv_layer_2.vhd
}
read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/ip/fifo_45/fifo_45.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_45/fifo_45.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_45/fifo_45_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/ip/fifo_45/fifo_45.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/ip/fifo_16/fifo_16.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_16/fifo_16.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_16/fifo_16_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/ip/fifo_16/fifo_16.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top conv_layer_2 -part xc7z020clg484-1


write_checkpoint -force -noxdef conv_layer_2.dcp

catch { report_utilization -file conv_layer_2_utilization_synth.rpt -pb conv_layer_2_utilization_synth.pb }
