# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing.xdc

# IP: /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/activation_fifo/activation_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==activation_fifo || ORIG_REF_NAME==activation_fifo}]
