# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nezin/Documents/ECE395A/vhdl/ip/fifo_45/fifo_45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_45 || ORIG_REF_NAME==fifo_45}]
