# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.cache/wt [current_project]
set_property parent.project_path /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/nezin/helpers/conv_2/conv_2_test_rom.coe
add_files /home/nezin/Documents/ECE395A/vhdl/helpers/conv_2/conv_2_test_rom.coe
add_files /home/nezin/Documents/ECE395A/vhdl/conv/coefs/conv0_1.coe
add_files /home/nezin/Documents/ECE395A/vhdl/conv/coefs/conv0_0.coe
add_files /home/nezin/Documents/ECE395A/vhdl/coefficients/rom.coe
add_files /home/nezin/Documents/ECE395A/vhdl/coefficients/conv1_ram_q.coe
add_files /home/nezin/Documents/ECE395A/vhdl/helpers/unit.coe
add_files /home/nezin/Documents/ECE395A/vhdl/coefficients/conv1_ram_i.coe
add_files /home/nezin/Documents/ECE395A/vhdl/coefficients/fc_layer.coe
add_files /home/nezin/Documents/ECE395A/vhdl/coefficients/fc_truncated_layer.coe
add_files /home/nezin/Documents/ECE395A/vhdl/coefficients/fc_truncated_reshape_layer.coe
add_files /home/nezin/Documents/ECE395A/vhdl/coefficients/fc_truncated_reshape_flipped_layer.coe
add_files /home/nezin/Documents/ECE395A/vhdl/coefficients/fc_16bit_layer.coe
add_files /home/nezin/Documents/ECE395A/vhdl/coefficients/fc_12bit_layer.coe
read_vhdl -library xil_defaultlib {
  /home/nezin/Documents/ECE395A/vhdl/source/conv2_controller.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/conv_0.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/conv_1.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/conv_layer_0.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/conv_layer_1.vhd
  /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/new/conv_layer_2.vhd
  /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/new/conv_relu_pool.vhd
  /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/new/conv_unit.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/dot.vhd
  /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/new/dot_n.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/downsample.vhd
  /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/new/matmul.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/maxpool_1.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/mux2_1.vhd
  /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/new/mux_3.vhd
  /home/nezin/Documents/ECE395A/vhdl/source/relu.vhd
  /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/new/sbl_dsp.vhd
  /home/nezin/Documents/ECE395A/vhdl/slope_bias_loader/slope_bias_loader.srcs/sources_1/new/slope_bias_loader.vhd
  /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/new/maia.vhd
}
read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/activation_fifo/activation_fifo.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/activation_fifo/activation_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/activation_fifo/activation_fifo_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/activation_fifo/activation_fifo.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/ip/fifo_16/fifo_16.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_16/fifo_16.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_16/fifo_16_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/ip/fifo_16/fifo_16.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_0/fir128_0.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_0/fir128_0_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_0/fir128_0.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_7680/fifo_7680.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_7680/fifo_7680.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_7680/fifo_7680_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_7680/fifo_7680.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/ip/fifo_45/fifo_45.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_45/fifo_45.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_45/fifo_45_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/ip/fifo_45/fifo_45.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/ip/fifo_generator_0/fifo_generator_0.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_1/fir128_1.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_1/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_1/fir128_1_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_relu_pool/conv_relu_pool.srcs/sources_1/ip/fir128_1/fir128_1.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_generator_1_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_generator_1_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_generator_1_1/fifo_generator_1_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_generator_1_1/fifo_generator_1.xci]

read_ip -quiet /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files /home/nezin/Documents/ECE395A/vhdl/matmul/matmul.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/constrs_1/new/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top maia -part xc7z020clg484-1


write_checkpoint -force -noxdef maia.dcp

catch { report_utilization -file maia_utilization_synth.rpt -pb maia_utilization_synth.pb }
