# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24.xci
# IP: The module: 'fifo_16x24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16x24'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16x24'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24.xci
# IP: The module: 'fifo_16x24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16x24'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/nezin/Documents/ECE395A/vhdl/conv_2_layer/conv_2_layer.srcs/sources_1/ip/fifo_16x24/fifo_16x24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16x24'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
