# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nezin/Documents/ECE395A/vhdl/maia/maia.srcs/sources_1/ip/fir128_1_1/fir128_1.xci
# IP: The module: 'fir128_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/ECE395A/vhdl/maia/maia.srcs/sources_1/ip/fir128_1_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir128_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/nezin/Documents/ECE395A/vhdl/maia/maia.srcs/sources_1/ip/fir128_1_1/fir128_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir128_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/nezin/Documents/ECE395A/vhdl/maia/maia.srcs/sources_1/ip/fir128_1_1/fir128_1.xci
# IP: The module: 'fir128_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nezin/Documents/ECE395A/vhdl/maia/maia.srcs/sources_1/ip/fir128_1_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir128_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/nezin/Documents/ECE395A/vhdl/maia/maia.srcs/sources_1/ip/fir128_1_1/fir128_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir128_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
