# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.cache/wt [current_project]
set_property parent.project_path /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.srcs/sources_1/new/vector.vhd
  /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.srcs/sources_1/new/inner_product.vhd
  /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.srcs/sources_1/new/matrix.vhd
  /home/bcv/Documents/ECE395A/vhdl/helpers/matrix_a.vhd
  /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.srcs/sources_1/new/matrix_multiply.vhd
  /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.srcs/sources_1/new/multiply.vhd
  /home/bcv/Documents/ECE395A/vhdl/helpers/vector_v.vhd
  /home/bcv/Documents/ECE395A/vhdl/helpers/vector_w.vhd
  /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.srcs/sources_1/new/simple_nn.vhd
  /home/bcv/Documents/ECE395A/vhdl/simple_nn/simple_nn.srcs/sources_1/new/neural_net_testbed.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top neural_net_testbed -part xc7z020clg484-1


write_checkpoint -force -noxdef neural_net_testbed.dcp

catch { report_utilization -file neural_net_testbed_utilization_synth.rpt -pb neural_net_testbed_utilization_synth.pb }
