# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/nezin/Documents/ECE395A/vhdl/argmax/argmax.cache/wt [current_project]
set_property parent.project_path /home/nezin/Documents/ECE395A/vhdl/argmax/argmax.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/nezin/Documents/ECE395A/vhdl/argmax/argmax.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/nezin/Documents/ECE395A/vhdl/argmax/argmax.srcs/sources_1/imports/new/vector.vhd
  /home/nezin/Documents/ECE395A/vhdl/argmax/argmax.srcs/sources_1/new/argmax.vhd
  /home/nezin/Documents/ECE395A/vhdl/argmax/argmax.srcs/sources_1/new/argmax_tb.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top argmax_tb -part xc7z020clg484-1


write_checkpoint -force -noxdef argmax_tb.dcp

catch { report_utilization -file argmax_tb_utilization_synth.rpt -pb argmax_tb_utilization_synth.pb }
