# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bcv/Documents/ECE395A/vhdl/inner_product/inner_product.srcs/sources_1/ip/mac/mac.xci
# IP: The module: 'mac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bcv/Documents/ECE395A/vhdl/inner_product/inner_product.srcs/sources_1/ip/mac/mac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/bcv/Documents/ECE395A/vhdl/inner_product/inner_product.srcs/sources_1/ip/mac/mac.xci
# IP: The module: 'mac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bcv/Documents/ECE395A/vhdl/inner_product/inner_product.srcs/sources_1/ip/mac/mac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
